# fly.toml app configuration file generated for matrix on 2024-02-18T09:44:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'matrix'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
